# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vizu/info.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Info(object):
    def setupUi(self, Info):
        Info.setObjectName("Info")
        Info.resize(400, 300)
        Info.setMinimumSize(QtCore.QSize(400, 300))
        Info.setMaximumSize(QtCore.QSize(400, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("vizu/../doc/img/logo/NorseVPN.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Info.setWindowIcon(icon)
        self.btn_close = QtWidgets.QPushButton(Info)
        self.btn_close.setGeometry(QtCore.QRect(309, 270, 83, 25))
        self.btn_close.setObjectName("btn_close")
        self.textBrowser = QtWidgets.QTextBrowser(Info)
        self.textBrowser.setGeometry(QtCore.QRect(10, 10, 381, 251))
        self.textBrowser.setObjectName("textBrowser")
        self.btn_showLog = QtWidgets.QPushButton(Info)
        self.btn_showLog.setGeometry(QtCore.QRect(10, 270, 83, 25))
        self.btn_showLog.setObjectName("btn_showLog")

        self.retranslateUi(Info)
        QtCore.QMetaObject.connectSlotsByName(Info)

    def retranslateUi(self, Info):
        _translate = QtCore.QCoreApplication.translate
        Info.setWindowTitle(_translate("Info", "Info"))
        self.btn_close.setText(_translate("Info", "Close"))
        self.btn_showLog.setText(_translate("Info", "Show Log"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Info = QtWidgets.QWidget()
    ui = Ui_Info()
    ui.setupUi(Info)
    Info.show()
    sys.exit(app.exec_())
