# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vizu/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NorseVPN(object):
    def setupUi(self, NorseVPN):
        NorseVPN.setObjectName("NorseVPN")
        NorseVPN.setEnabled(True)
        NorseVPN.resize(799, 600)
        NorseVPN.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("vizu/../doc/img/logo/NorseVPN_app.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        NorseVPN.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(NorseVPN)
        self.centralwidget.setObjectName("centralwidget")
        self.cb_connected = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_connected.setEnabled(False)
        self.cb_connected.setGeometry(QtCore.QRect(736, 10, 40, 23))
        self.cb_connected.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.cb_connected.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("vizu/icons/white_link.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cb_connected.setIcon(icon1)
        self.cb_connected.setCheckable(True)
        self.cb_connected.setAutoExclusive(False)
        self.cb_connected.setTristate(False)
        self.cb_connected.setObjectName("cb_connected")
        self.btn_connect = QtWidgets.QPushButton(self.centralwidget)
        self.btn_connect.setGeometry(QtCore.QRect(700, 560, 83, 25))
        self.btn_connect.setObjectName("btn_connect")
        self.btn_debug = QtWidgets.QPushButton(self.centralwidget)
        self.btn_debug.setGeometry(QtCore.QRect(600, 560, 83, 25))
        self.btn_debug.setObjectName("btn_debug")
        self.btn_config = QtWidgets.QPushButton(self.centralwidget)
        self.btn_config.setGeometry(QtCore.QRect(752, 40, 31, 25))
        self.btn_config.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("vizu/icons/white_settings.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_config.setIcon(icon2)
        self.btn_config.setObjectName("btn_config")
        self.tree_location = QtWidgets.QTreeWidget(self.centralwidget)
        self.tree_location.setGeometry(QtCore.QRect(10, 20, 281, 561))
        self.tree_location.setObjectName("tree_location")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(310, 140, 311, 311))
        self.textBrowser.setMarkdown("")
        self.textBrowser.setObjectName("textBrowser")
        self.btn_shuffle = QtWidgets.QPushButton(self.centralwidget)
        self.btn_shuffle.setGeometry(QtCore.QRect(300, 20, 31, 25))
        self.btn_shuffle.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("vizu/icons/white_shuffle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_shuffle.setIcon(icon3)
        self.btn_shuffle.setObjectName("btn_shuffle")
        self.label_version = QtWidgets.QLabel(self.centralwidget)
        self.label_version.setEnabled(False)
        self.label_version.setGeometry(QtCore.QRect(340, 570, 120, 20))
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_version.setFont(font)
        self.label_version.setAlignment(QtCore.Qt.AlignCenter)
        self.label_version.setObjectName("label_version")
        self.btn_info = QtWidgets.QPushButton(self.centralwidget)
        self.btn_info.setGeometry(QtCore.QRect(710, 40, 31, 25))
        self.btn_info.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("vizu/icons/white_info.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_info.setIcon(icon4)
        self.btn_info.setObjectName("btn_info")
        NorseVPN.setCentralWidget(self.centralwidget)

        self.retranslateUi(NorseVPN)
        QtCore.QMetaObject.connectSlotsByName(NorseVPN)

    def retranslateUi(self, NorseVPN):
        _translate = QtCore.QCoreApplication.translate
        NorseVPN.setWindowTitle(_translate("NorseVPN", "NorseVPN"))
        self.cb_connected.setToolTip(_translate("NorseVPN", "checked you are currently connected to a vpn"))
        self.btn_connect.setText(_translate("NorseVPN", "Connect"))
        self.btn_debug.setText(_translate("NorseVPN", "Debug"))
        self.tree_location.headerItem().setText(0, _translate("NorseVPN", "Location"))
        self.label_version.setText(_translate("NorseVPN", "Version v0.00.00"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NorseVPN = QtWidgets.QMainWindow()
    ui = Ui_NorseVPN()
    ui.setupUi(NorseVPN)
    NorseVPN.show()
    sys.exit(app.exec_())
